// <auto-generated />
using HotelListing.Dev.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.Dev.API.Migrations
{
    [DbContext(typeof(HotelListingDBContext))]
    [Migration("20230330142656_Seed Data to table Hotel and Country")]
    partial class SeedDatatotableHotelandCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListing.Dev.API.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(199)
                        .HasColumnType("nvarchar(199)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "India",
                            ShortName = "IN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United State Of America",
                            ShortName = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        });
                });

            modelBuilder.Entity("HotelListing.Dev.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(199)
                        .HasColumnType("nvarchar(199)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "City Square, Mumbai",
                            CountryId = 1,
                            Description = "5 Star Hotel",
                            Name = "Taj Hotel",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Address = "City Center, California",
                            CountryId = 2,
                            Description = "5 Star Hotel",
                            Name = "Hollywood Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "Eight Square, London",
                            CountryId = 3,
                            Description = "8 Star Hotel",
                            Name = "British Heritage Hotel",
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("HotelListing.Dev.API.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Dev.API.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.Dev.API.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
